import axios from 'axios'
import React, { useEffect, useState } from 'react'
import Footer from '../Footer/Footer'
import Navbar from './Navbar'

const AboutUs = () => {
  const [data , setData] = useState("")
  const about =  `${process.env.REACT_APP_APIENDPOINTNEW}user/welcome/aboutUs`
  useEffect(()=>{
    axios.get(about).then((res)=>{
      setData(res.data?.results)
    })
  },[])
  return (
    <div>
      <Navbar/>
    <div className=" bg-whitem-2 p-5" >
      <>
  <h1> ABOUT US for STAR IMPORTERS</h1>
  <p>
   {data[0]?.description}
  </p>
  <p>
    <strong>Children's Information</strong>
    <br />
    We believe it is important to provide added protection for children online.
    We encourage parents and guardians to spend time online with their children
    to observe, participate in and/or monitor and guide their online activity.
    <br />
    [YOUR SITE URL] does not knowingly collect any personally identifiable
    information from children under the age of 13. If a parent or guardian
    believes that [YOUR SITE URL] has in its database the
    personally-identifiable information of a child under the age of 13, please
    contact us immediately (using the contact in the first paragraph) and we
    will use our best efforts to promptly remove such information from our
    records.
  </p>
  <p>
    <b>Online Privacy Policy Only</b>
    <br />
    This privacy policy applies only to our online activities and is valid for
    visitors to our website and regarding information shared and/or collected
    there.
    <br />
    This policy does not apply to any information collected offline or via
    channels other than this website.
  </p>
  <p>
    <b>Consent</b>
    <br />
    By using our website, you hereby consent to our privacy policy and agree to
    its terms.
  </p>
  <p>
    <b>Update</b>
    <br />
    This Privacy Policy was last updated on: Nov 1st, 2019. Should we update,
    amend or make any changes to our privacy policy, those changes will be
    posted here.
  </p>
  <p>
    {/* END of Privacy Policy || Generated by http://www.PrivacyPolicyOnline.com || */}
  </p>
  <p></p>
</>

    </div>
    <Footer/>
    </div>
  )
}

export default AboutUs
